/**
 * Generates the SHARED newsletter content via Claude API.
 *
 * Architecture: one Claude call per week for the shared sections
 * (market / community / features). Per-user stats are NOT generated by Claude —
 * they're rendered from a fixed template at send time with the user's own numbers.
 * This keeps cost flat regardless of subscriber count.
 *
 * Model: Opus 4.7 with adaptive thinking. Override via NEWSLETTER_MODEL env var
 * if cost becomes an issue (e.g. set to "claude-sonnet-4-6").
 */

import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import type {
  MarketNewsData,
  CommunityStats,
  FeatureUpdate,
} from "./collectors";

// ============================================================
// Public types
// ============================================================

export interface SharedNewsletterData {
  market: MarketNewsData;
  community: CommunityStats;
  features: FeatureUpdate[];
}

// Zod schema for the structured output Claude returns.
// SDK's messages.parse() validates the response against this.
const NewsletterSchema = z.object({
  subject: z
    .string()
    .max(80)
    .describe("Email subject line. Concise, no clickbait, traders' tone."),
  intro: z
    .string()
    .describe("Short greeting + one-sentence theme of the week. 2-3 sentences max."),
  marketSection: z.object({
    title: z.string().describe("Heading for the market section, e.g. 'This Week in the Markets'"),
    body: z
      .string()
      .describe(
        "2-3 short paragraphs of market commentary based on the week's date, season, and typical macro themes. Mention upcoming holidays if relevant. Avoid making up specific data points like prices or % moves — write thematically."
      ),
  }),
  communitySection: z.object({
    title: z.string().describe("Heading for community stats"),
    body: z.string().describe("1-2 paragraphs interpreting the community numbers"),
    highlight: z
      .string()
      .describe(
        "Single most interesting stat or insight, rendered as a punchy one-liner"
      ),
  }),
  featuresSection: z.object({
    title: z.string().describe("Heading for product updates"),
    items: z
      .array(
        z.object({
          title: z.string().describe("Short title for this update"),
          description: z
            .string()
            .describe("1-2 sentences explaining what changed and why traders care"),
        })
      )
      .max(5)
      .describe("Top 3-5 user-facing updates. Skip pure refactors or internal changes."),
  }),
  outro: z
    .string()
    .describe("Closing: 1-2 sentences + sign-off. Friendly but professional."),
});

export type GeneratedNewsletter = z.infer<typeof NewsletterSchema>;

// ============================================================
// Claude client
// ============================================================

let _client: Anthropic | null = null;
function getClient(): Anthropic {
  if (_client) return _client;
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY not configured");
  _client = new Anthropic({ apiKey });
  return _client;
}

// ============================================================
// System prompt — frozen instructions + style guide.
// Caching this prefix saves ~90% on input cost when iterating during dev.
// (Weekly cron won't hit cache TTL between runs — that's expected.)
// ============================================================

const SYSTEM_PROMPT = `You are the editorial voice of TJ TradeHub — a trading journal product for retail forex, futures, and indices traders.

You write the weekly newsletter sent to subscribers every Monday. It recaps the week, surfaces community activity, and highlights product updates.

TONE & STYLE:
- Trader-to-trader. Direct. Confident. No marketing fluff.
- Concise — every sentence earns its place. If a section has nothing meaningful to say, keep it brief rather than padding.
- No corporate hype words ("revolutionary", "game-changing", "leverage synergies").
- Skip generic platitudes ("Markets are unpredictable!"). Assume the reader is an active trader who already knows the basics.
- Active voice. Short sentences mixed with longer analytical ones.
- US English. No emoji.

CONTENT RULES:
- Market section: Write thematically about typical market drivers for the given week (seasonality, calendar themes, holidays affecting liquidity). DO NOT fabricate specific prices, percentages, or news events you weren't given.
- Community section: Interpret the numbers, don't just restate them. If the week had low activity (e.g. <5 trades), acknowledge it honestly rather than spinning.
- Features section: Translate raw git commit messages into user-benefit language. Skip commits that are pure refactoring, dependency updates, typo fixes, or internal admin tooling unless they affect users. If fewer than 3 meaningful items, return only what's real — don't pad.
- Subject line: 6-10 words. Specific, not generic. No "Weekly Update" / "Newsletter #4" style.

You return structured JSON matching the provided schema. Nothing else.`;

// ============================================================
// Generator
// ============================================================

export async function generateNewsletter(
  data: SharedNewsletterData
): Promise<GeneratedNewsletter> {
  const client = getClient();
  const model = process.env.NEWSLETTER_MODEL || "claude-opus-4-7";

  const userPrompt = buildUserPrompt(data);

  const response = await client.messages.parse({
    model,
    max_tokens: 16000,
    thinking: { type: "adaptive" },
    system: [
      {
        type: "text",
        text: SYSTEM_PROMPT,
        cache_control: { type: "ephemeral" },
      },
    ],
    messages: [{ role: "user", content: userPrompt }],
    output_config: {
      format: zodOutputFormat(NewsletterSchema),
      effort: "high",
    },
  });

  if (!response.parsed_output) {
    throw new Error(
      `Claude returned no parsed_output. stop_reason=${response.stop_reason}`
    );
  }

  return response.parsed_output;
}

// ============================================================
// User prompt builder — formats the week's data for Claude
// ============================================================

function buildUserPrompt(data: SharedNewsletterData): string {
  const { market, community, features } = data;

  const lines: string[] = [];

  lines.push(`Generate the newsletter for the week of ${market.weekStart} to ${market.weekEnd}.`);
  lines.push("");

  // Market data
  lines.push("## Week's market context");
  if (market.holidaysThisWeek.length > 0) {
    lines.push(
      `NYSE closures this week: ${market.holidaysThisWeek.map((h) => `${h.name} (${h.date})`).join(", ")}`
    );
  } else {
    lines.push("No NYSE closures this week.");
  }
  if (market.upcomingHolidays.length > 0) {
    const next = market.upcomingHolidays[0];
    lines.push(`Next upcoming closure: ${next.name} on ${next.date} (${next.daysAway} days away).`);
  }
  lines.push("");

  // Community stats
  lines.push("## Community stats (last 7 days)");
  lines.push(`- Total trades journaled: ${community.totalTrades}`);
  lines.push(`- Active traders: ${community.activeTraders}`);
  lines.push(`- New signups this week: ${community.newUsers}`);
  lines.push(`- Total users on platform: ${community.totalUsers}`);
  if (community.winRate !== null) {
    lines.push(`- Community win rate: ${community.winRate}%`);
  }
  if (community.totalPnl !== null) {
    lines.push(`- Community aggregate P&L: ${community.totalPnl >= 0 ? "+" : ""}${community.totalPnl.toFixed(2)}`);
  }
  if (community.topSymbols.length > 0) {
    lines.push(
      `- Top traded symbols: ${community.topSymbols.map((s) => `${s.symbol} (${s.count})`).join(", ")}`
    );
  }
  lines.push("");

  // Features / commits
  lines.push("## Recent commits (raw git log — filter to user-facing changes only)");
  if (features.length === 0) {
    lines.push("No commits this week. Either skip this section or mention quietly that the team focused on planning.");
  } else {
    for (const f of features) {
      lines.push(`- ${f.hash}: ${f.message}`);
    }
  }

  return lines.join("\n");
}
